### PR TITLE
Feature/2 main container

### PR DESCRIPTION
**Pull request by Yazanmuf**

### CODE REVIEW

**Comment by mmosta** [comment]
Great work so far.

Take look at the additional details in the issue.

**Review by mmosta — CHANGES_REQUESTED** [review]
Update to call the HN API and fetch the list of top stories and their titles

**Comment by Yazanmuf** [comment]
Whats a reasonable number of fetch requests a page can make?
I am not finding request url that returns the top stories with their titles(and other details) in one json object.
Is it ok to get one list of all story ids? then use a for loop to get the title for each?

**Comment by mmosta** [comment]
Yes, thats just the way it is unfortunately.

Lets limit it to top 10 stories for now

**Comment by Yazanmuf** [comment]
Hey, I did  a pull request but it looks like it stays on the same page? because there is an older one with the same requirements?
Let me know if I did something wrong/

**Pull request merged**
